### PR TITLE
Decouple halt from test runner

### PR DESCRIPTION
**Pull request by varnerac**
Adds do_run_tests() and do_halt(result), allowing a user run tests, execute a cleanup action, then halt the runtime with the appropriate exit code.

### CODE REVIEW

**Comment by varnerac** [comment]
The Javascript target fails for me with :

```
λ ~/gleeunit/ split_test_runner_and_halt* gleam test
  Compiling gleeunit
   Compiled in 0.01s
    Running gleeunit_test.main
file:///Users/varnerac/gleeunit/build/dev/javascript/gleeunit/gleeunit.mjs:15
    if (result.isOk()) {
               ^

TypeError: result.isOk is not a function
    at file:///Users/varnerac/gleeunit/build/dev/javascript/gleeunit/gleeunit.mjs:15:16
    at halt (file:///Users/varnerac/gleeunit/build/dev/javascript/gleeunit/gleeunit.mjs:29:5)
    at Module.main (file:///Users/varnerac/gleeunit/build/dev/javascript/gleeunit/gleeunit.mjs:6:10)
    at Module.main (file:///Users/varnerac/gleeunit/build/dev/javascript/gleeunit/gleeunit_test.mjs:5:20)
    at [eval]:1:83

Node.js v18.4.0
```

That corresponds to the Gleam code:

```gleam
  let code = case result {
    Ok(_) -> 0
    Error(_) -> 1
  }
```

Is that a JS code generation bug or mistake on my side?

**Comment by varnerac** [comment]
I’m running into issues because `run_tests()` returns a Promise. I could make the run test result an opaque Dynamic value. Another option could be passing in `setup() -> Result(resources,Nil)` and `tear_down(resources) -> Nil` functions. `resources` could be `Nil` or hold resources like ports, PIDs, or files that need cleanup.

**Comment by lpil** [comment]
The promise issue is a tricky one. I'm not sure how we could handle that other than providing an `after_complete` callback or something? Not an API I'm a huge fan of.

**Comment by varnerac** [comment]
No need. I figured out I can create a custom type and pass a different fixture structure with a test description, setup, and tear-down functions. I can even pass a list of tests in instead of a single using a tuple.

**Comment by lpil** [comment]
Fab!

**Pull request closed without merging**
